### ISSUE TITLE
EPIC: Student account

### ISSUE THREAD

**Issue by Bruna-Andelieri** [Bruna-Andelieri/rock-in-class#10]
### Epic Description

This Epic addresses the tasks of creating and updating student accounts.

### User Stories

- [x] https://github.com/Bruna-Andelieri/rock-in-class/issues/4
- [x] https://github.com/Bruna-Andelieri/rock-in-class/issues/5
- [x] https://github.com/Bruna-Andelieri/rock-in-class/issues/7
- [ ] https://github.com/Bruna-Andelieri/rock-in-class/issues/8
