### ISSUE TITLE
EPIC: Manage booking

### ISSUE THREAD

**Issue by Bruna-Andelieri** [Bruna-Andelieri/rock-in-class#13]
### Epic Description

This Epic addresses the tasks of creating, updating, and deleting student bookings.

### User Stories

- [x] https://github.com/Bruna-Andelieri/rock-in-class/issues/6
- [x] https://github.com/Bruna-Andelieri/rock-in-class/issues/11
- [x] https://github.com/Bruna-Andelieri/rock-in-class/issues/12
