### ISSUE TITLE
EPIC: Admin management

### ISSUE THREAD

**Issue by Bruna-Andelieri** [Bruna-Andelieri/rock-in-class#9]
### Epic Description

This Epic addresses the tasks of creating, updating, and deleting tutor profiles and bookings.

### User Stories

- [x] https://github.com/Bruna-Andelieri/rock-in-class/issues/1#issue-2083805591
- [x] https://github.com/Bruna-Andelieri/rock-in-class/issues/2#issue-2083814930
- [x] https://github.com/Bruna-Andelieri/rock-in-class/issues/3#issue-2083823071
